[project]
name = "sudoku"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aws-cdk-lib>=2.212.0",
    "constructs>=10.4.2",
    "flask>=3.1.2",
    "mangum>=0.19.0",
    "pyinstaller>=6.15.0",
]
