name: Build Windows Executable

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    
    - name: Install dependencies
      run: uv sync
    
    - name: Build Windows executable
      run: |
        pyinstaller --onefile --console --name SudokuGame-Windows src/desktop/sudoku_app.py --add-data "src/web/templates;templates" --add-data "src/core/sudoku.py;."
    
    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: SudokuGame-Windows
        path: dist/SudokuGame-Windows.exe
        
  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    
    - name: Install dependencies
      run: uv sync
    
    - name: Build macOS executable
      run: |
        pyinstaller --onefile --console --name SudokuGame-macOS src/desktop/sudoku_app.py --add-data "src/web/templates:templates" --add-data "src/core/sudoku.py:."
    
    - name: Upload macOS executable
      uses: actions/upload-artifact@v4
      with:
        name: SudokuGame-macOS
        path: dist/SudokuGame-macOS
        
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    
    - name: Install dependencies
      run: uv sync
    
    - name: Build Linux executable
      run: |
        pyinstaller --onefile --console --name SudokuGame-Linux src/desktop/sudoku_app.py --add-data "src/web/templates:templates" --add-data "src/core/sudoku.py:."
    
    - name: Upload Linux executable
      uses: actions/upload-artifact@v4
      with:
        name: SudokuGame-Linux
        path: dist/SudokuGame-Linux